### ISSUE TITLE
move to JuliaPhysics

### ISSUE THREAD

**Issue by Roger-luo** [JuliaPhysics/Lattices.jl#14]
a few things need to be revised after the move:

- [x] change README
- [ ] check CI & doc builds

Update: link to docs is broken...somehow

**Comment by crstnbr** [comment]
After the move, perhaps the documentation should also not be linked to your personal website anymore? Why not have it as github.io?

**Comment by Roger-luo** [comment]
because it is broken at the moment somehow :-(

**Comment by Roger-luo** [comment]
I think CI and doc build is transferred as well now. @giordano can I have ownership to the org as well? I need to change the link to doc in this repo title.

**Comment by crstnbr** [comment]
I changed the link to the doc (it's working). Feel free to reopen if there is something left to do here.
