### ISSUE TITLE
Fixed or Open

### ISSUE THREAD

**Issue by Roger-luo** [JuliaPhysics/Lattices.jl#15]
I think in a lot places it is called `open boundary` instead of `fixed`? But it might be too general to use `Open` as the name of boundary type.

and I'm wondering if the default boundary condition should be open?

**Comment by crstnbr** [comment]
I prefer `open` over `fixed`. Also, I think that periodic boundaries are much more common than open ones in physics applications. I wouldn't want to change the default.
