### ISSUE TITLE
Do not make lattice size a type parameter

### ISSUE THREAD

**Issue by GiggleLiu** [JuliaPhysics/Lattices.jl#22]
I think a static lattice size type parameters can make the compiler unhappy (type polution). Is there any paractical using case that we can get significant performance gain by making it static?

e.g.

https://github.com/JuliaPhysics/Lattices.jl/blob/68dca5c5786554630eafcf86073266b98d0819f1/src/square/Square.jl#L15

**Comment by Roger-luo** [comment]
No actually it's made to be members in another implementation. I think this was copied from a pre 1.0 old package.

**Comment by Roger-luo** [comment]
should be fixed by new design now #23
