### ISSUE TITLE
Implement to_index/to_indices for Coordinate type

### ISSUE THREAD

**Issue by emerali** [JuliaPhysics/Lattices.jl#33]
Would allow users to index an array using the Coordinate type

**Comment by emerali** [comment]
I'm realizing we might just be able to use `CartesianIndex` in place of `Coordinate` since it supports everything we need (addition/subtraction). Need to make sure we aren't creating `Coordinate{N, <:AbstractFloat}` anywhere though.

**Comment by emerali** [comment]
I added the restriction `Coordinate{N, T <: Integer}` to the type definition, and the test suite still works fine.

Probably a good idea to switch over.

**Comment by Roger-luo** [comment]
I think we shouldn't allow `Coordinate` to be indexable, since when indexing an Array that contains some information of sites/bonds/etc. we need a unique identifier to index the array, but coordinates are not unique identifiers.
